# docker-compose.ci.yml


services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepassword
    # No ports mapped to avoid collisions on port 5432 in CI
    # ports:
    #   - "5432:5432"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: recipe_db
      DB_USER: postgres
      DB_PASSWORD: somepassword
    # Removed "command: ['./migrate.sh']" so the Dockerfile's default CMD is used

  api:
    build: .
    depends_on:
      - db
      - migrate
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: recipe_db
      DB_USER: postgres
      DB_PASSWORD: somepassword
    ports:
      - "8080:8080"
    entrypoint: []
    command: ["go", "run", "cmd/api-gateway/main.go"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  grpc-server:
    build: .
    command: ["go", "run", "cmd/grpc-server/main.go"]
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 50051 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
