# docker-compose.ci.yaml
services:
  api:
    environment:
      - CI=true
      - DB_HOST=localhost
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile.migrate
    command: ["go", "run", "cmd/migrate/main.go"]
    networks:
      - backend
    environment:
      - PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
      - CI=true
    depends_on:
      postgres:
        condition: service_healthy
  grpc-server:
    environment:
      - DB_HOST=localhost

networks:
  backend:
    external: false
    name: backend
    driver: bridge
