# docker-compose.ci.yaml
services:
  # Do not override postgres here – the GA service container is used.
  api:
    environment:
      - CI=true
      - DB_HOST=localhost
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile.migrate
    command: ["go", "run", "cmd/migrate/main.go"]
    networks:
      - backend
    environment:
      - PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
      - CI=true
    # Remove the dependency on postgres since we aren’t using Compose’s Postgres.
    # depends_on:
    #   postgres:
    #     condition: service_healthy
  grpc-server:
    environment:
      - DB_HOST=localhost

networks:
  backend:
    driver: bridge
