FROM golang:1.20-alpine

WORKDIR /workspace

# Copy just go.mod & go.sum first, to cache module downloads
COPY go.mod go.sum ./
RUN go mod download

# Then copy the rest of the code
COPY . ./

# Default CMD is a no-op; the test command is specified by Compose:
CMD ["echo", "Ready to run tests"] 