# docker-compose.ci.yml


services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepassword
    # No "ports" here. We rely on internal Docker networking.
    # ports:
    #   - "5432:5432"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: recipe_db
      DB_USER: postgres
      DB_PASSWORD: somepassword
    # Removed "command: ['./migrate.sh']" so the Dockerfile's default CMD is used

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - migrate
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: recipe_db
      DB_USER: postgres
      DB_PASSWORD: somepassword
    ports:
      - "8080:8080"
    entrypoint: []
    command: ["go", "run", "cmd/api-gateway/main.go"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  grpc-server:
    build: .
    depends_on:
      - db
      - migrate
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: recipe_db
      DB_USER: postgres
      DB_PASSWORD: somepassword
    # Remove network_mode: host
    # Optionally expose port if you need to talk externally:
    ports:
      - "50051:50051"
    command: ["go", "run", "cmd/grpc-server/main.go"]
    healthcheck:
      test: ["CMD-SHELL", "nc -z grpc-server 50051 || exit 1"] 
      interval: 10s
      timeout: 5s
      retries: 5

  #
  # New "test" service to run "go test" inside the same Docker network as 'db'
  #
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
      - migrate
      - grpc-server
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: recipe_db
      DB_USER: postgres
      DB_PASSWORD: somepassword
      GRPC_SERVER_ADDR: grpc-server:50051
    command: ["go", "test", "./...", "-v"]
