# docker-compose.ci.yml
version: '3.9'

services:
  api:
    build: .
    entrypoint: []
    command: ["go", "run", "cmd/api-gateway/main.go"]
    networks:
      - backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
      - CI=true
    depends_on: []  # override postgres dependency

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    command: ["go", "run", "cmd/migrate/main.go"]
    networks:
      - backend
    environment:
      - PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
      - CI=true
    depends_on: []  # override postgres dependency

  grpc-server:
    build: .
    command: ["go", "run", "cmd/grpc-server/main.go"]
    networks:
      - backend
    ports:
      - "50051:50051"
      - "50052:50052"
      - "50053:50053"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
    depends_on: []  # override postgres dependency

networks:
  backend:
    driver: bridge
