# docker-compose.ci.yml
services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    command: ["go", "run", "cmd/migrate/main.go"]
    environment:
      - PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
    network_mode: host
    # Note: This container is a one-off job. Its exit code determines success.
    
  api:
    build: .
    entrypoint: []
    command: ["go", "run", "cmd/api-gateway/main.go"]
    environment:
      - PORT=8080
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
      - SKIP_MIGRATIONS=true
    network_mode: host
    depends_on:
      - migrate
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  grpc-server:
    build: .
    command: ["go", "run", "cmd/grpc-server/main.go"]
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
      - JWT_SECRET=your_jwt_secret
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 50051 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
