name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  COMPOSE_PROJECT_NAME: recipe-book-api-v2
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true
  GRPC_DIAL_ADDRESS: localhost:50051
  GODEBUG: netdns=go

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Debug Docker Compose Config
        run: docker compose -f docker-compose.ci.yml config

      - name: Build Docker images
        run: docker compose -f docker-compose.ci.yml build --no-cache

      - name: Run Database Migrations
        run: docker compose -f docker-compose.ci.yml run migrate

      - name: Start API and gRPC Services
        run: docker compose -f docker-compose.ci.yml up -d api grpc-server

      - name: Download wait-for-it.sh script
        run: |
          curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh

      - name: Wait for 'users' table
        run: |
          echo "Waiting for 'users' table in DB..."
          for i in {1..30}; do
            RESULT=$(
              docker run --rm \
                --network recipe-book-api-v2_default \
                -e PGPASSWORD=somepassword \
                postgres:14 \
                psql -h db -U postgres -w -d recipe_db -t \
                  -c "SELECT to_regclass('public.users');" \
              | tr -d '[:space:]'
            )
            echo "Attempt $i: Result: '$RESULT'"
            if [ "$RESULT" = "users" ]; then
              echo "'users' table exists."
              exit 0
            fi
            sleep 2
          done
          echo "'users' table not found after waiting."
          exit 1

      - name: List Docker Compose Services
        run: docker compose -f docker-compose.ci.yml ps

      - name: Wait for API to be Ready
        run: |
          URL="http://localhost:8080/healthcheck"
          echo "Checking API health at: $URL"
          sleep 30
          for i in {1..20}; do
            if nc -z localhost 8080; then
              status=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
              echo "HTTP status: $status"
              if [ "$status" -eq 200 ]; then
                echo "API is ready"
                exit 0
              fi
            fi
            sleep 5
          done
          echo "API did not become healthy in time"
          exit 1

      - name: Run Go tests
        env:
          DB_HOST: db
          GODEBUG: netdns=go
        run: go test -v ./...

      - name: Run E2E tests with Newman
        run: |
          for file in $(find collections/user_endpoints -name "*.postman_collection.json"); do
            docker run --rm --network host -v $(pwd):/etc/newman postman/newman run "$file" --environment collections/TestEnvironment.postman_environment.json
          done

      - name: Dump container logs
        if: always()
        run: docker compose -f docker-compose.ci.yml logs

      - name: Run integration tests with Newman
        run: |
          for file in $(find collections/user_endpoints -name "*.postman_collection.json"); do
            echo "Running Postman tests in $file"
            docker run --rm \
              --network recipe-book-api-v2_default \
              -v $(pwd):/etc/newman \
              postman/newman run "$file" \
              --environment collections/TestEnvironment.postman_environment.json
          done

      - name: Tear Down Docker Compose Services
        if: always()
        run: docker compose -f docker-compose.ci.yml down -v
